// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuitteaxttwenjwclkxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aXR0ZWF4dHR3ZW5qd2Nsa3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjIzMjYsImV4cCI6MjA2Mjc5ODMyNn0.1cAeEmrFn9EQdlfEfWpgKHj6oNztjDZtIsWkUVd7BEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);